name             'lamp'
maintainer       'Alex Crawford'
maintainer_email 'acrawford@cmdagency.com'
license          'All rights reserved'
description      'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
version          '0.1.0'

depends 'build-essential'
depends 'apt'
depends 'git'
depends 'php'
depends 'apache2'
depends 'nginx'
depends 'mysql'
depends 'composer'
depends 'nodejs'
depends 'rvm'